<?php

return [
    'Actualités' => [
        'Numérama' => 'https://www.numerama.com/feed',
        'Presse-citron' => 'http://www.presse-citron.net/feed/',
        'Le journal du Geek' => 'http://www.journaldugeek.com/feed/',
        'Korben' => 'https://korben.info/feed',
        'Tom\'s Guide' => 'http://www.tomsguide.fr/feeds/rss2/tom-s-guide-fr,20-0.xml',
        'Clubic' => 'http://www.clubic.com/articles.rss',
        'Framasoft' => 'http://www.framablog.org/index.php/feed/atom',
        'Phoronix' => 'https://www.phoronix.com/rss.php',
        'LinuxFR' => 'http://linuxfr.org/news.atom',
        'Standblog' => 'http://standblog.org/blog/feed/rss2',
        'FrAndroid' => 'https://www.frandroid.com/feed/atom',
        'Le monde informatique' => 'http://www.lemondeinformatique.fr/flux-rss/rss.xml',
        'Minimachines' => 'http://www.minimachines.net/feed/atom',
    ],
    'Développement (général)' => [
        'Mozilla Hacks' => 'https://hacks.mozilla.org/feed/',
        'Mozilla Gfx' => 'https://mozillagfx.wordpress.com/feed/',
        'alsacreations' => 'http://www.alsacreations.com/rss/actualites.xml',
        'A list apart' => 'https://alistapart.com/main/feed',
        'quirksmode' => 'http://www.quirksmode.org/blog/atom.xml',
        'mediumequalsmessage.com' => 'http://feeds.feedburner.com/mediumequalsmessage/cwebbdesign',
        'DailyJS' => 'https://medium.com/feed/dailyjs',
        'Javascript Weekly' => 'http://javascriptweekly.com/rss',
        'HTML5 Weekly' => 'http://html5weekly.com/rss',
    ],
    'Développement (techno/lib/framework)' => [
        'Wordpress' => 'https://wordpress.org/news/feed/',
        'Wordpress dev' => 'https://developer.wordpress.org/news/feed/',
        'Drupal' => 'https://www.drupal.org/section-blog/2603760/feed',
        'Spip' => 'http://blog.spip.net/spip.php?page=backend',
        'Symfony' => 'https://feeds.feedburner.com/symfony/blog',
        'Rollup' => 'https://github.com/rollup/rollup/releases.atom',
        'Brunch' => 'https://github.com/brunch/brunch/releases.atom',
        'Svelte' => 'https://svelte.dev/blog/rss.xml',
        'VueJS' => 'https://medium.com/feed/the-vue-point',
        'React' => 'https://reactjs.org/feed.xml',
    ],
    'Logiciels' => [
        'Capyloon' => 'https://capyloon.org/releases.xml',
        'Deno' => 'https://github.com/denoland/deno/releases.atom',
        'NodeJS' => 'https://nodejs.org/en/feed/blog.xml',
        'Docker' => 'https://www.docker.com/blog/feed/',
        'Rust' => 'https://blog.rust-lang.org/feed.xml',
        'Google Chrome Releases' => 'http://feeds.feedburner.com/GoogleChromeReleases',
    ],
];
